services:
  subconverter:
    build: .
    container_name: subconverter
    restart: unless-stopped
    ports:
      # 左边是 VPS 对外端口，右边是容器内端口
      - "25500:25500"
    environment:
      - PORT=25500
      - HOST=0.0.0.0
